baseURL = "https://suihan74.github.io/blog/"
languageCode = "ja"
title = "すいはんブログ.io"
theme = "github-style"
publishDir = "blog"

[params]
  author = "すいはん"
  description = "ほげげ"
  github = "suihan74"
  twitter = "suihan742"
  email = "suihan742@gmail.com"
  utterances = "suihan74.github.io"
  avatar = "https://avatars0.githubusercontent.com/u/5970984?s=460&v=4"
  url = "https://suihan74.github.io/blog"
